name: 'Zap/Snyk Security scan'
description: 'Syncs Zap/Snyk Security scan output with Jira issues'
author: 'MAC-FC'
inputs:
  # Jira
  jira-username:
    description: 'Jira username that will be the reporter of issues created when syncing'
    required: true
  jira-token:
    description: 'Jira token corresponding to the jira-username input with permission to manage issues for the target Jira project'
    required: true
  jira-project-key:
    description: 'Jira project key where issues will be created'
    required: true
  jira-host:
    description: 'Host of the target Jira instance'
    required: true
  jira-issue-type:
    description: 'jira issue type e.g. task, story ...'
    required: true
  jira-custom-field-key-value:
    description: 'JSON string of Jira custom field keys/values, e.g. { "customfield_14117": "example-value" }'
    required: false
  jira-labels:
    description: 'Jira issue labels'
  jira-title-prefix:
    description: 'Jira issue title prefix to apply'
  is_jira_enterprise:
    description: 'is the Jira instance enterprise, set true if it is enterprise and false if otherwise'
    required: true
  assign-jira-ticket-to:
    description: 'the assignee accountId to assign the Jira ticket to}'
    required: false
  min-severity:
    description: 'minimum severity level that Jira tickets should be created for (acceptable values are "low", "medium", "high", and "critical")'
    required: false
    default: 'low'
# Scan
  zap-risk-code:
    description: 'riskcode type to report'
    required: false
  scan-output-path:
    description: 'the path to zap sacn output'
    required: true
  scan-type:
    description: 'can type to perform "snyk" or "zap"'
    required: false
    default: 'snyk'
  major-version-only: 
    description: 'ticket in jira will be created only for the major version of vulnerability package; can be "true" or "false"'
    required: false
    default: 'false'
runs:
  using: node16
  main: dist/index.js
