name: Jira Ticket Creation Workflow
on:
  push:
    branches:
      - remove-node-module
  pull_request:
    branches: [ main ]
jobs:
  create_ticket:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: OWASP ZAP Baseline Scan
        continue-on-error: true
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: "https://www.zaproxy.org/"

      - name: Install Jira library and packages for Node.js
        run: |
            npm install jira-client
            npm install @actions/core

      - name: Run Jira Ticket Creator
        uses: ./
        with:
          jira-username: ${{ secrets.WORKSPACE_EMAIL }}
          jira-token: ${{ secrets.API_TOKEN }}
          jira-host: arayateklu.atlassian.net
          jira-project-key: ZAP
          jira-issue-type: Task
          jira-labels: test,zap
          jira-title-prefix: '[MCFC] - Zap :'
          zap-risk-code: '3'
          scan-output-path: 'report_json.json'
          scan-type: 'zap'
              
