name: Jira Ticket Creation Workflow
on:
  push:
    branches:
      - main
      - add-assignee
  pull_request:
    branches: [ main ]

jobs:
  create_ticket:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        continue-on-error: true
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "https://www.zaproxy.org/"

      - name: Run Jira Ticket Creator
        uses: ./
        with:
          jira-username: ${{ secrets.WORKSPACE_EMAIL }}
          jira-token: ${{ secrets.API_TOKEN }}
          jira-host: arayateklu.atlassian.net
          jira-project-key: MAC
          jira-issue-type: Task
          jira-labels: test,zap
          jira-title-prefix: '[MACFC] - Zap : '
          assign-jira-ticket-to: '712020:d17f0d00-fb3b-4b4b-b778-0249dd16559d'
          zap-risk-code: '3'
          scan-output-path: 'report_json.json'
          scan-type: 'zap'