name: Check Sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build distribution
        run: |
          npm install -g @vercel/ncc
          ncc build src/index.js --license licenses.txt --out temp

      - name: Check file sync
        run: |
          ls temp/
          diff -q temp/index.js dist/index.js
          exit_code=$?

          if [ $exit_code -eq 0 ]; then
            echo "The 'index.js' file and 'dist/index.js' file are in sync."
          else
            echo "ERROR: The 'index.js' file and 'dist/index.js' file are not in sync."
            exit 1
          fi
