name: Jira Ticket Creation Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]


jobs:
  create_ticket:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        continue-on-error: true
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://www.zaproxy.org/"

      - name: Run Jira Ticket Creator
        uses: ./
        with:
          jira-username: ${{ secrets.WORKSPACE_EMAIL }}
          jira-token: ${{ secrets.API_TOKEN }}
          jira-host: arayateklu.atlassian.net
          jira-project-key: MAC
          jira-issue-type: Epic
          jira-labels: test,zap
          jira-title-prefix: '[MACFC] - Zap : '
          # jira-custom-field-key-value: ''
          assign-jira-ticket-to: ${{ secrets.ACCOUNT_ID_AT }}
          is_jira_enterprise: false
          zap-risk-code: '3'
          scan-output-path: 'report_json.json'
          scan-type: 'zap' 
