name: Jira Ticket Creation Workflow
on:
  push:
    branches:
      - main
      - jira-enterp-support
  pull_request:
    branches: [ main ]

jobs:
  create_ticket:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        continue-on-error: true
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "https://www.zaproxy.org/"

      - name: Run Jira Ticket Creator
        uses: ./
        with:
          jira-username: "TTHO"
          jira-token: ${{ secrets.JIRA_NET_BEARER_TOKEN }}
          jira-host: "jiraent.cms.gov"
          jira-project-key: "EREGCSC"
          jira-issue-type: "Bug"
          jira-labels: "test,zap"
          jira-title-prefix: '[EREGCSC] - Zap : '
          assign-jira-ticket-to: "TTHO"
          zap-risk-code: '3'
          scan-output-path: 'report_json.json'
          scan-type: 'zap' 